"""baseline full schema

Revision ID: e21895a59f7d
Revises:
Create Date: 2026-06-04 23:07:44.953681

Baseline: full schema from empty.

Existing deployments whose schema was built by db.create_all() + the old chain
must run ONCE, instead of `upgrade head`:

    flask db stamp e21895a59f7d

This marks the existing schema as already at the baseline without re-creating
tables. Fresh/empty databases use the normal `flask db upgrade head`.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e21895a59f7d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_trace_artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('span_id', sa.String(length=36), nullable=True),
    sa.Column('artifact_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('mime_type', sa.String(length=80), nullable=True),
    sa.Column('storage_uri', sa.String(length=500), nullable=True),
    sa.Column('preview_text', sa.Text(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_trace_artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_trace_artifacts_artifact_type'), ['artifact_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_trace_artifacts_span_id'), ['span_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_trace_artifacts_trace_id'), ['trace_id'], unique=False)

    op.create_table('agent_trace_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('span_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_trace_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_trace_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_trace_events_span_id'), ['span_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_trace_events_trace_id'), ['trace_id'], unique=False)

    op.create_table('agent_trace_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('link_type', sa.String(length=50), nullable=False),
    sa.Column('target_table', sa.String(length=80), nullable=False),
    sa.Column('target_id', sa.String(length=120), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_trace_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_trace_links_link_type'), ['link_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_trace_links_trace_id'), ['trace_id'], unique=False)

    op.create_table('agent_trace_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('legacy_run_id', sa.String(length=36), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('agent_type', sa.String(length=30), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('chat_task_id', sa.String(length=36), nullable=True),
    sa.Column('workflow_run_id', sa.String(length=36), nullable=True),
    sa.Column('eval_run_id', sa.Integer(), nullable=True),
    sa.Column('eval_case_id', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('input_preview', sa.Text(), nullable=True),
    sa.Column('output_preview', sa.Text(), nullable=True),
    sa.Column('error_type', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=80), nullable=True),
    sa.Column('tokens_input', sa.Integer(), nullable=False),
    sa.Column('tokens_output', sa.Integer(), nullable=False),
    sa.Column('cost_cny', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('total_latency_ms', sa.Integer(), nullable=True),
    sa.Column('llm_latency_ms', sa.Integer(), nullable=True),
    sa.Column('tool_latency_ms', sa.Integer(), nullable=True),
    sa.Column('mcp_latency_ms', sa.Integer(), nullable=True),
    sa.Column('sandbox_latency_ms', sa.Integer(), nullable=True),
    sa.Column('budget_json', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_trace_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_trace_runs_agent_type'), ['agent_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_trace_runs_chat_task_id'), ['chat_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_trace_runs_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_trace_runs_eval_case_id'), ['eval_case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_trace_runs_eval_run_id'), ['eval_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_trace_runs_legacy_run_id'), ['legacy_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_trace_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_trace_runs_trace_id'), ['trace_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_agent_trace_runs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_trace_runs_workflow_run_id'), ['workflow_run_id'], unique=False)

    op.create_table('agent_trace_spans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('parent_span_id', sa.String(length=36), nullable=True),
    sa.Column('span_type', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('input_preview', sa.Text(), nullable=True),
    sa.Column('output_preview', sa.Text(), nullable=True),
    sa.Column('error_type', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('tokens_input', sa.Integer(), nullable=True),
    sa.Column('tokens_output', sa.Integer(), nullable=True),
    sa.Column('cost_cny', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_trace_spans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_trace_spans_parent_span_id'), ['parent_span_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_trace_spans_span_type'), ['span_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_trace_spans_trace_id'), ['trace_id'], unique=False)

    op.create_table('ai_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agent_type', sa.String(length=20), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('input_preview', sa.String(length=200), nullable=True),
    sa.Column('injection_detected', sa.Boolean(), nullable=True),
    sa.Column('injection_pattern', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eval_case_grader_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_run_id', sa.String(length=36), nullable=False),
    sa.Column('grader_type', sa.String(length=50), nullable=False),
    sa.Column('grader_name', sa.String(length=80), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost_cny', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eval_case_grader_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eval_case_grader_results_case_run_id'), ['case_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_eval_case_grader_results_grader_type'), ['grader_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_eval_case_grader_results_trace_id'), ['trace_id'], unique=False)

    op.create_table('eval_case_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('eval_run_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.String(length=120), nullable=False),
    sa.Column('case_type', sa.String(length=30), nullable=True),
    sa.Column('suite', sa.String(length=50), nullable=True),
    sa.Column('agent_type', sa.String(length=30), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('failure_type', sa.String(length=50), nullable=True),
    sa.Column('input_preview', sa.Text(), nullable=True),
    sa.Column('output_preview', sa.Text(), nullable=True),
    sa.Column('tokens_input', sa.Integer(), nullable=True),
    sa.Column('tokens_output', sa.Integer(), nullable=True),
    sa.Column('cost_cny', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eval_case_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eval_case_runs_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_eval_case_runs_case_type'), ['case_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_eval_case_runs_eval_run_id'), ['eval_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_eval_case_runs_failure_type'), ['failure_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_eval_case_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_eval_case_runs_suite'), ['suite'], unique=False)
        batch_op.create_index(batch_op.f('ix_eval_case_runs_trace_id'), ['trace_id'], unique=False)

    op.create_table('eval_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suite_name', sa.String(length=50), nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=True),
    sa.Column('model_name', sa.String(length=50), nullable=True),
    sa.Column('total_cases', sa.Integer(), nullable=True),
    sa.Column('passed_cases', sa.Integer(), nullable=True),
    sa.Column('pass_rate', sa.Float(), nullable=True),
    sa.Column('results_json', sa.JSON(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('role', sa.Enum('STUDENT', 'TEACHER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('ai_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agent_type', sa.String(length=20), nullable=False),
    sa.Column('context_type', sa.String(length=20), nullable=True),
    sa.Column('context_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classrooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('mcp_api_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('rate_limit_rpm', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mcp_api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_api_keys_key_hash'), ['key_hash'], unique=False)

    op.create_table('problems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_problems_slug'), ['slug'], unique=True)

    op.create_table('quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('error_patterns', sa.JSON(), nullable=True),
    sa.Column('knowledge_map', sa.JSON(), nullable=True),
    sa.Column('recent_topics', sa.JSON(), nullable=True),
    sa.Column('recent_questions', sa.JSON(), nullable=True),
    sa.Column('current_hint_level', sa.JSON(), nullable=True),
    sa.Column('learning_summary', sa.Text(), nullable=True),
    sa.Column('preferred_language', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('teacher_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('preferred_difficulty', sa.String(length=20), nullable=True),
    sa.Column('preferred_language', sa.String(length=20), nullable=True),
    sa.Column('preferred_topics', sa.JSON(), nullable=True),
    sa.Column('style_notes', sa.Text(), nullable=True),
    sa.Column('class_weak_areas', sa.JSON(), nullable=True),
    sa.Column('class_level', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id')
    )
    op.create_table('agent_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('task_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('agent_type', sa.String(length=20), nullable=False),
    sa.Column('input_params', sa.JSON(), nullable=False),
    sa.Column('plan_steps', sa.JSON(), nullable=True),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('review_status', sa.String(length=20), nullable=True),
    sa.Column('review_feedback', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classroom_quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('allow_late_submission', sa.Boolean(), nullable=True),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('classroom_id', 'quiz_id', name='unique_classroom_quiz')
    )
    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'classroom_id', name='unique_student_classroom')
    )
    op.create_table('mcp_audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_key_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tool_name', sa.String(length=50), nullable=False),
    sa.Column('tool_args', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['mcp_api_keys.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mcp_tool_approvals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('api_key_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tool_name', sa.String(length=50), nullable=False),
    sa.Column('tool_args', sa.JSON(), nullable=False),
    sa.Column('risk_level', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['mcp_api_keys.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('programming_language', sa.String(length=20), nullable=False),
    sa.Column('starter_code', sa.Text(), nullable=True),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('solution_explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('problem_id', 'programming_language', name='uq_question_problem_language')
    )
    op.create_table('quiz_problems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quiz_id', 'problem_id', name='unique_quiz_problem')
    )
    op.create_table('test_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('input', sa.Text(), nullable=False),
    sa.Column('expected_output', sa.Text(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agent_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('input_message', sa.Text(), nullable=True),
    sa.Column('input_context', sa.JSON(), nullable=True),
    sa.Column('output_response', sa.Text(), nullable=True),
    sa.Column('total_latency_ms', sa.Integer(), nullable=True),
    sa.Column('llm_latency_ms', sa.Integer(), nullable=True),
    sa.Column('tool_latency_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_input', sa.Integer(), nullable=True),
    sa.Column('tokens_output', sa.Integer(), nullable=True),
    sa.Column('tool_call_count', sa.Integer(), nullable=True),
    sa.Column('tool_calls_json', sa.JSON(), nullable=True),
    sa.Column('error_type', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('llm_retries', sa.Integer(), nullable=True),
    sa.Column('tool_retries', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['ai_messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_message_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('agent_type', sa.String(length=20), nullable=False),
    sa.Column('routed_agent', sa.String(length=20), nullable=True),
    sa.Column('result_message_id', sa.Integer(), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ),
    sa.ForeignKeyConstraint(['result_message_id'], ['ai_messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_message_id'], ['ai_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_question_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('question_data', sa.JSON(), nullable=False),
    sa.Column('validation_status', sa.String(length=20), nullable=True),
    sa.Column('validation_details', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('revision_count', sa.Integer(), nullable=True),
    sa.Column('published_question_id', sa.Integer(), nullable=True),
    sa.Column('published_problem_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ),
    sa.ForeignKeyConstraint(['published_problem_id'], ['problems.id'], ),
    sa.ForeignKeyConstraint(['published_question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('classroom_quiz_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['classroom_quiz_id'], ['classroom_quizzes.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('execution_time', sa.Float(), nullable=True),
    sa.Column('memory_used', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_run_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(length=20), nullable=True),
    sa.Column('tool_name', sa.String(length=50), nullable=True),
    sa.Column('tool_input', sa.JSON(), nullable=True),
    sa.Column('tool_output_preview', sa.Text(), nullable=True),
    sa.Column('tool_success', sa.Boolean(), nullable=True),
    sa.Column('llm_prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('llm_completion_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('actual_output', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('execution_time', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('chat_task_id', sa.String(length=36), nullable=True),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('workflow_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('plan_json', sa.JSON(), nullable=True),
    sa.Column('current_step_index', sa.Integer(), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('max_steps', sa.Integer(), nullable=True),
    sa.Column('max_retries_per_step', sa.Integer(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('total_tokens_used', sa.Integer(), nullable=True),
    sa.Column('total_latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_task_id'], ['chat_tasks.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_run_id', sa.String(length=36), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(length=30), nullable=False),
    sa.Column('agent_type', sa.String(length=30), nullable=True),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('risk_level', sa.String(length=10), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('depends_on', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflow_steps')
    op.drop_table('workflow_runs')
    op.drop_table('test_results')
    op.drop_table('agent_run_steps')
    op.drop_table('submissions')
    op.drop_table('quiz_attempts')
    op.drop_table('generated_question_drafts')
    op.drop_table('chat_tasks')
    op.drop_table('agent_runs')
    op.drop_table('test_cases')
    op.drop_table('quiz_problems')
    op.drop_table('questions')
    op.drop_table('mcp_tool_approvals')
    op.drop_table('mcp_audit_logs')
    op.drop_table('enrollments')
    op.drop_table('classroom_quizzes')
    op.drop_table('ai_messages')
    op.drop_table('agent_tasks')
    op.drop_table('teacher_preferences')
    op.drop_table('student_profiles')
    op.drop_table('quizzes')
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_problems_slug'))

    op.drop_table('problems')
    with op.batch_alter_table('mcp_api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_api_keys_key_hash'))

    op.drop_table('mcp_api_keys')
    op.drop_table('classrooms')
    op.drop_table('ai_conversations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('eval_runs')
    with op.batch_alter_table('eval_case_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eval_case_runs_trace_id'))
        batch_op.drop_index(batch_op.f('ix_eval_case_runs_suite'))
        batch_op.drop_index(batch_op.f('ix_eval_case_runs_status'))
        batch_op.drop_index(batch_op.f('ix_eval_case_runs_failure_type'))
        batch_op.drop_index(batch_op.f('ix_eval_case_runs_eval_run_id'))
        batch_op.drop_index(batch_op.f('ix_eval_case_runs_case_type'))
        batch_op.drop_index(batch_op.f('ix_eval_case_runs_case_id'))

    op.drop_table('eval_case_runs')
    with op.batch_alter_table('eval_case_grader_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eval_case_grader_results_trace_id'))
        batch_op.drop_index(batch_op.f('ix_eval_case_grader_results_grader_type'))
        batch_op.drop_index(batch_op.f('ix_eval_case_grader_results_case_run_id'))

    op.drop_table('eval_case_grader_results')
    op.drop_table('ai_audit_logs')
    with op.batch_alter_table('agent_trace_spans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_trace_spans_trace_id'))
        batch_op.drop_index(batch_op.f('ix_agent_trace_spans_span_type'))
        batch_op.drop_index(batch_op.f('ix_agent_trace_spans_parent_span_id'))

    op.drop_table('agent_trace_spans')
    with op.batch_alter_table('agent_trace_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_trace_runs_workflow_run_id'))
        batch_op.drop_index(batch_op.f('ix_agent_trace_runs_user_id'))
        batch_op.drop_index(batch_op.f('ix_agent_trace_runs_trace_id'))
        batch_op.drop_index(batch_op.f('ix_agent_trace_runs_status'))
        batch_op.drop_index(batch_op.f('ix_agent_trace_runs_legacy_run_id'))
        batch_op.drop_index(batch_op.f('ix_agent_trace_runs_eval_run_id'))
        batch_op.drop_index(batch_op.f('ix_agent_trace_runs_eval_case_id'))
        batch_op.drop_index(batch_op.f('ix_agent_trace_runs_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_agent_trace_runs_chat_task_id'))
        batch_op.drop_index(batch_op.f('ix_agent_trace_runs_agent_type'))

    op.drop_table('agent_trace_runs')
    with op.batch_alter_table('agent_trace_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_trace_links_trace_id'))
        batch_op.drop_index(batch_op.f('ix_agent_trace_links_link_type'))

    op.drop_table('agent_trace_links')
    with op.batch_alter_table('agent_trace_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_trace_events_trace_id'))
        batch_op.drop_index(batch_op.f('ix_agent_trace_events_span_id'))
        batch_op.drop_index(batch_op.f('ix_agent_trace_events_event_type'))

    op.drop_table('agent_trace_events')
    with op.batch_alter_table('agent_trace_artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_trace_artifacts_trace_id'))
        batch_op.drop_index(batch_op.f('ix_agent_trace_artifacts_span_id'))
        batch_op.drop_index(batch_op.f('ix_agent_trace_artifacts_artifact_type'))

    op.drop_table('agent_trace_artifacts')
    # ### end Alembic commands ###
