from .codes import MCPErrorCode
from .exceptions import (
    MCPError,
    MCPAuthRequired,
    MCPPermissionDenied,
    MCPScopeDenied,
    MCPRateLimited,
    MCPApprovalRequired,
    MCPApprovalPending,
    MCPApprovalRejected,
    MCPToolNotFound,
    MCPSchemaInvalid,
    MCPArgumentInvalid,
    MCPTransportUnavailable,
    MCPToolTimeout,
    MCPInternalError,
)

__all__ = [
    "MCPErrorCode",
    "MCPError",
    "MCPAuthRequired",
    "MCPPermissionDenied",
    "MCPScopeDenied",
    "MCPRateLimited",
    "MCPApprovalRequired",
    "MCPApprovalPending",
    "MCPApprovalRejected",
    "MCPToolNotFound",
    "MCPSchemaInvalid",
    "MCPArgumentInvalid",
    "MCPTransportUnavailable",
    "MCPToolTimeout",
    "MCPInternalError",
]
