"""Canonical MCP error codes."""

from enum import Enum


class MCPErrorCode(str, Enum):
    AUTH_REQUIRED = "MCP_AUTH_REQUIRED"
    PERMISSION_DENIED = "MCP_PERMISSION_DENIED"
    SCOPE_DENIED = "MCP_SCOPE_DENIED"
    RATE_LIMITED = "MCP_RATE_LIMITED"
    APPROVAL_REQUIRED = "MCP_APPROVAL_REQUIRED"
    APPROVAL_PENDING = "MCP_APPROVAL_PENDING"
    APPROVAL_REJECTED = "MCP_APPROVAL_REJECTED"
    TOOL_NOT_FOUND = "MCP_TOOL_NOT_FOUND"
    SCHEMA_INVALID = "MCP_SCHEMA_INVALID"
    ARGUMENT_INVALID = "MCP_ARGUMENT_INVALID"
    TRANSPORT_UNAVAILABLE = "MCP_TRANSPORT_UNAVAILABLE"
    TOOL_TIMEOUT = "MCP_TOOL_TIMEOUT"
    INTERNAL_ERROR = "MCP_INTERNAL_ERROR"

    @property
    def retryable(self) -> bool:
        return self in _RETRYABLE

    @property
    def http_status(self) -> int:
        return _HTTP_STATUS.get(self, 500)


_RETRYABLE = {
    MCPErrorCode.RATE_LIMITED,
    MCPErrorCode.TRANSPORT_UNAVAILABLE,
    MCPErrorCode.TOOL_TIMEOUT,
}

_HTTP_STATUS = {
    MCPErrorCode.AUTH_REQUIRED: 401,
    MCPErrorCode.PERMISSION_DENIED: 403,
    MCPErrorCode.SCOPE_DENIED: 403,
    MCPErrorCode.RATE_LIMITED: 429,
    MCPErrorCode.APPROVAL_REQUIRED: 202,
    MCPErrorCode.APPROVAL_PENDING: 202,
    MCPErrorCode.APPROVAL_REJECTED: 403,
    MCPErrorCode.TOOL_NOT_FOUND: 404,
    MCPErrorCode.SCHEMA_INVALID: 422,
    MCPErrorCode.ARGUMENT_INVALID: 422,
    MCPErrorCode.TRANSPORT_UNAVAILABLE: 503,
    MCPErrorCode.TOOL_TIMEOUT: 504,
    MCPErrorCode.INTERNAL_ERROR: 500,
}
